apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ecommerce-ui.yaml
  - product-catalog.yaml
  - order-management.yaml
  - product-inventory.yaml
  - profile-management.yaml
  - shipping-handling.yaml
  - contact-support.yaml
  - istio-gateway.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
